@BasePath = api/auth
@DevHabitApiHostAddress = https://localhost:5001
@refreshTokenFromLogin = {{login.response.body.refreshToken}}
@token = {{login.response.body.refreshToken}}


### Register a User

POST {{DevHabitApiHostAddress}}/{{BasePath}}/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "TestUserr",
  "email": "test@mail.com",
  "password": "Az123456!",
  "confirmationPassword": "Az123456!"
}

### Login a User

# @name login
POST {{DevHabitApiHostAddress}}/{{BasePath}}/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "Az123456!"
}

### Refresh a User Tokens

# @name refresh
POST {{DevHabitApiHostAddress}}/{{BasePath}}/refresh HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "{{refreshTokenFromLogin}}"
}

### Logout

# @name logout
POST {{DevHabitApiHostAddress}}/{{BasePath}}/logout HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "{{refreshTokenFromLogin}}"
}
