@BasePath = api/habits
@DevHabitApiHostAddress = https://localhost:5001
@ResourceId = h_019b1071-dd2c-7f72-864e-0a2475c17490
@token = {{login.response.body.accessToken}}


###

# @Fields = fields=id,name,createdAtUtc
# @token = {{refresh.response.body.accessToken}}
 

### Get Habits

GET {{DevHabitApiHostAddress}}/{{BasePath}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

### Get Habit by Id

GET {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/vnd.dev-habit.hateoas+json

### Create Habit

POST {{DevHabitApiHostAddress}}/{{BasePath}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "hurl better than kulala",
  "description": null,
  "type": 2,
  "frequency": {
    "type": 2,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 30,
    "unit": "minutes"
  }
}

### Update Habit

PUT {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

### Partially Update Habit

PATCH {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

### Delete Habit

DELETE {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
