@BasePath = api/tags
@DevHabitApiHostAddress = https://localhost:5001
@ResourceId = t_019b265a-77ca-7904-8674-fe2732868803
@token = {{login.response.body.accessToken}}
# @token = {{refresh.response.body.accessToken}}


### Get Tags

GET {{DevHabitApiHostAddress}}/{{BasePath}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/vnd.dev-habit.hateoas+json

### Get Tag by Id

GET {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/vnd.dev-habit.hateoas+json

### Create Tag

POST {{DevHabitApiHostAddress}}/{{BasePath}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "hurl",
  "description": null
}

### Update Tag

PUT {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

### Delete Tag

DELETE {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
