@BasePath = api/users
@DevHabitApiHostAddress = https://localhost:5001
@ResourceId = 7a4b6979-70a4-4d97-b815-3f18f43ba6be
@token = {{login.response.body.accessToken}}


###

# @token = {{refresh.response.body.accessToken}}
 

### Get User by Id

GET {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

### Get Current User

GET {{DevHabitApiHostAddress}}/{{BasePath}}/me HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
