@basePath = api/habits
@devHabitApiHostAddress = https://localhost:5001
@habitId = h_019b1071-dd2c-7f72-864e-0a2475c17490


### Get Habits

GET {{devHabitApiHostAddress}}/{{basePath}} HTTP/1.1
Content-Type: application/vnd.devhabit.hateoas+json



### Get Habit by Id

GET {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}} HTTP/1.1
Accept: application/json



### Create Habit

POST {{devHabitApiHostAddress}}/{{basePath}} HTTP/1.1
Content-Type: application/vnd.devhabit.hateoas+json

{
  "description": null,
  "endDate": "2025-12-30",
  "frequency": {
    "timesPerPeriod": 1,
    "type": 2
  },
  "milestone": {
    "target": 1
  },
  "name": "Kulala custom type such",
  "target": {
    "unit": "minutes",
    "value": 30
  },
  "type": 2
}

### Update Habit

PUT {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "The new description",
  "frequency": {
    "timesPerPeriod": 1,
    "type": 2
  },
  "milestone": {
    "target": 100
  },
  "name": "Daily coding",
  "target": {
    "unit": "minutes",
    "value": 30
  },
  "type": 2
}

### Partially Update Habit

PATCH {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "op": "replace",
    "path": "/name",
    "value": "Daily Coding (Update)"
  },
  {
    "op": "remove",
    "path": "/description"
  }
]

### Delete Habit

DELETE {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}} HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
